### PR TITLE
Alphabet scroller

### PR DESCRIPTION
**Pull request by essy16**
I have added an alphabet scroller

### CODE REVIEW

**Comment by The-Repo-Club** [comment]
@essy16 would you mind adding this into my fork if you have time if not I'll go about reverse engineering it and work it out :)

**Comment by essy16** [comment]
Hey how do I do so...

**Comment by The-Repo-Club** [comment]
Clone and do the same if you don't have the time I can look through the changes and do it :)

**Comment by essy16** [comment]
Uhm well is there another way because I have a lot of pending projects to be completed

**Comment by The-Repo-Club** [comment]
Ya it's fine I'll look though the diff and do it myself thanks for the patch though

**Pull request merged**
