### PR TITLE
Create strings.xml

### PR DESCRIPTION
**Pull request by orestisfra**
Greek locale

### CODE REVIEW

**Comment by Ilithy** [comment]
Hello, if you don't mind, it would be very helpful and nice to also add your work to this Fork: https://github.com/jooooscha/Olauncher
_(my apologies, the Strings.xml file differs slightly, but for the better ;-)_
 It already supports multiple languages :).

my apologies for the inconvenience.

**Comment by orestisfra** [comment]
> Hello, if you don't mind, it would be very helpful and nice to also add your work to this Fork: https://github.com/jooooscha/Olauncher _(my apologies, the Strings.xml file differs slightly, but for the better ;-)_ It already supports multiple languages :).
> 
> my apologies for the inconvenience.

no problem. done.

**Comment by Ilithy** [comment]
Thanks ❤️‍🔥

**Comment by orestisfra** [comment]
no problem I already ported it to match the fork. I will gladly help with any future changes

    Στις Δευτέρα 6 Ιουνίου 2022 - 12:20:39 μ.μ. EEST, ο χρήστης Ilithy ***@***.***> έγραψε:  
 
 


Hello, if you don't mind, it would be very helpful and nice to also add your work to this Fork: https://github.com/jooooscha/Olauncher
(my apologies, the Strings.xml file differs slightly, but for the better ;-)
It already supports multiple languages :).

my apologies for the inconvenience.

**Pull request merged**
