### PR TITLE
Enable Haptic Feedback

### PR DESCRIPTION
**Pull request by shalzz**

### CODE REVIEW

**Comment by Ilithy** [comment]
Hi @shalzz If I may ask, with this PR, is the activation or deactivation of the haptic feedback only managed by the operating system?

Thank you, my apologies for the inconvenience

**Comment by shalzz** [comment]
> Hi @shalzz If I may ask, with this PR, is the activation or deactivation of the haptic feedback only managed by the operating system?
> 
> Thank you, my apologies for the inconvenience

If there is an option of disabling system-wide vibration/haptic feedback, then this PR should respect that. Let me know if it doesn't.

**Comment by jooooscha** [comment]
I would gladly accept this PR :)

**Comment by shalzz** [comment]
@jooooscha You can already pull in my commits. A PR is just a github specific concept.

**Comment by jooooscha** [comment]
If you could open an PR, that would reduce the work for me. Also would it be easier to merge it into my code base and add and enable option to the settings

**Comment by Ilithy** [comment]
@jooooscha I made the PR (https://github.com/jooooscha/Olauncher/pull/50) by copying the work of @shalzz
Sorry I can't do more, I don't know how to add the activation/deactivation option in Olauncher CF settings :-/

**Comment by tanujnotes** [comment]
Haptic feedback was there in older versions but people complained about it being irritating.
Problem with haptic feedback is that the intensity is different on different phone models. While it is barely noticeable on my Samsung, it can vibrate violently on a Xiaomi device. For these reasons, we're skipping this it. All this has already been communicated to creator of the PR.

**Pull request closed without merging**
