### PR TITLE
Create Chinese Strings

### PR DESCRIPTION
**Pull request by sr093906**

### CODE REVIEW

**Comment by lichingyun** [comment]
@tanujnotes I don't know how to help you, I am italian. Maybe I can help you with the italian translation(how?)

**Comment by tanujnotes** [comment]
@lichingyun Thank you for the offer. I'll let you know once I start working on translations.

**Comment by Ilithy** [comment]
Hello @lichingyun If you want, new lines to translate in Chinese are present on the main branch, please keep your PR updated, thanks :-)

**Comment by lichingyun** [comment]
Hello,

I am italian, I cannot translate in chinese.Sorry

1 feb 2022 14:07:29 Ilithy ***@***.***>:

**Comment by Ilithy** [comment]
My apologies, as the PR was linked to a string.xml file in Chinese, I made a mistake, sorry again.

**Pull request closed without merging**
